baseURL = "https://leenamgyo.github.io/"
languageCode = "ko-kr"
title = "Namgyo Wiki"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowSummary = true
  mainSections = ["docs"]

[menu]
  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 1
  # [[menu.main]]
  #   name = "Search"
  #   url = "/search/"
  #   weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  
  